### ISSUE TITLE
ac.pl.umap error message "ValueError: no types given"

### ISSUE THREAD

**Issue by ad7115** [scverse/muon#108]
**Describe the bug**
I am running analysis on multiomic scRNA + scATAC sequencing data, but when plotting the ATAC UMAP, the same error message rises : "ValueError: no types given". 

Here is the whole output:

"ValueError                                Traceback (most recent call last)
<ipython-input-192-030fe1956a2a> in <module>
----> 1 ac.pl.umap(atac,use_raw=True,
      2            color='mt:ND3',
      3            ncols=4,
      4            color_map='plasma_r',
      5            colorbar_loc=None,

~/.local/lib/python3.8/site-packages/muon/_atac/plot.py in umap(data, **kwargs)
    197     See sc.pl.embedding for details.
    198     """
--> 199     return embedding(data, basis="umap", **kwargs)
    200 
    201 

~/.local/lib/python3.8/site-packages/muon/_atac/plot.py in embedding(data, basis, color, average, func, use_raw, layer, **kwargs)
    164             adata=adata, keys=keys, average=average, func=func, use_raw=use_raw, layer=layer
    165         )
--> 166         ad = AnnData(x, obs=adata.obs, obsm=adata.obsm)
    167         return sc.pl.embedding(ad, basis=basis, color=attr_names, **kwargs)
    168 

~/.local/lib/python3.8/site-packages/anndata/_core/anndata.py in __init__(self, X, obs, var, uns, obsm, varm, layers, raw, dtype, shape, filename, filemode, asview, obsp, varp, oidx, vidx)
    289             self._init_as_view(X, oidx, vidx)
    290         else:
--> 291             self._init_as_actual(
    292                 X=X,
    293                 obs=obs,

~/.local/lib/python3.8/site-packages/anndata/_core/anndata.py in _init_as_actual(self, X, obs, var, uns, obsm, varm, varp, obsp, raw, layers, dtype, shape, filename, filemode)
    433                 elif not isinstance(X.columns, pd.RangeIndex):
    434                     x_indices.append(("var", "columns", X.columns))
--> 435                 X = ensure_df_homogeneous(X, "X")
    436 
    437         # ----------------------------------------------------------------------

~/.local/lib/python3.8/site-packages/anndata/utils.py in ensure_df_homogeneous(df, name)
    137     # TODO: rename this function, I would not expect this to return a non-dataframe
    138     if all(isinstance(dt, pd.SparseDtype) for dt in df.dtypes):
--> 139         arr = df.sparse.to_coo().tocsr()
    140     else:
    141         arr = df.to_numpy()

/share/apps/python/3.8.6/intel/lib/python3.8/site-packages/pandas/core/arrays/sparse/accessor.py in to_coo(self)
    330         from scipy.sparse import coo_matrix
    331 
--> 332         dtype = find_common_type(self._parent.dtypes)
    333         if isinstance(dtype, SparseDtype):
    334             dtype = dtype.subtype

/share/apps/python/3.8.6/intel/lib/python3.8/site-packages/pandas/core/dtypes/cast.py in find_common_type(types)
   1462     """
   1463     if len(types) == 0:
-> 1464         raise ValueError("no types given")
   1465 
   1466     first = types[0]

ValueError: no types given"

**Comment by gtca** [comment]
Hey @ad7115,

Is there any reproducible example for this? At least listing all the data types involved (especially `.raw.X` and `.X` judging by the log?) should give an idea what exactly we can address.
I tested this on a few datasets and different versions of pandas and couldn't reproduce this so far.

**Comment by ad7115** [comment]
ok, i did some digging and figured it out. the problem was not with the data types. instead, the issue was the following: my genome is a RefSeq assembly, so scaffolds have underscores in their names, e.g. "NW_020229871.1". however, `mu.read_10x_h5` changes underscores to colons in `mdata["atac"].uns["atac"]['peak_annotation']`, but not in `mdata["atac"].var_names`!!! i suspect that this leads to no peaks being selected inside `_average_peaks` which is called by `embedding`, which is in turn called by `ac.pl.pca` and  `ac.pl.umap`. long story short, changing colons back to underscores fixes the issue:
```
atac.uns["atac"]["peak_annotation"]["peak"] = atac.uns["atac"]["peak_annotation"]["peak"].str.replace("NW:","NW_")
```
