### ISSUE TITLE
Is being developed?

### ISSUE THREAD

**Issue by GirayEryilmaz** [scverse/muon#121]
Greetings,

This is a great tool that I would like to use working with multi-modality-omics data (rna, atac and protein). However I need to understand, is muon (along with MuData) being actively developed and maintained? What are the plans for the future of this tool?

Best,
Giray

**Comment by gtca** [comment]
Hey @GirayEryilmaz,

Hope you find muon useful for your tasks! It is maintained, and more features will be coming soon as part of mudata and muon as well as other scverse packages. One of the directions of feature expansion would be more functionality to work with the atac-like modalities.

In case you might have any feature requests or suggestions that we might be able to accommodate as part of the roadmap, please feel free to share!

**Comment by GirayEryilmaz** [comment]
OK, thank you!
