### ISSUE TITLE
mu.pl.scatter() fails when providing color

### ISSUE THREAD

**Issue by SarahOuologuem** [scverse/muon#132]
Hi! 

I'm getting the following error when running mu.pl.scatter() with a provided color:

![muon_error](https://github.com/scverse/muon/assets/68101181/dedeaf40-a052-4ef8-bf0d-397f0ff094e1)

When setting `color=None`, the plotting function does not fail: 

<img src="https://github.com/scverse/muon/assets/68101181/9b335c8d-60f8-4f22-9dca-32aaf3079036" width=40% height=40%>

I also checked scanpy's `sc.pl.scatter()` and **it errors as described in scverse/scanpy#1986 and scverse/scanpy#311 when passing the color as a list.**

Therefore, **when deleting [line 75 (`color = [color]`)  in plot.py](https://github.com/scverse/muon/blob/master/muon/_core/plot.py#L75), i.e. passing the color as a string instead of a list to the function `sc.pl.scatter()`**, `mu.pl.scatter()` works completely fine and 

`mu.pl.scatter(data,"rna:CD4","rna:CD8A", color="rna:total_counts")` 

then produces: 

<img src="https://github.com/scverse/muon/assets/68101181/020fba54-f374-41e3-a437-2883d04237c2" width=40% height=40%>

**System**
 - Linux, Ubuntu
 - Python version: 3.10
 - Versions of libraries involved:
	- scanpy: 1.9.6
	- muon: 0.1.5

**Comment by gtca** [comment]
As discussed in #134, waiting for https://github.com/scverse/scanpy/issues/1986 to be resolved.

**Comment by gtca** [comment]
Fixed upstream thanks to @flying-sheep!
