### ISSUE TITLE
ImportError: cannot import name '_compute_connectivities_umap' from 'scanpy.neighbors' 

### ISSUE THREAD

**Issue by nbutyrate** [scverse/muon#135]
Python 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:36:46) 
[Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> 

I installed muon and tried to run one of the tutorial and got the following error, please help

>>> import numpy as np
>>> import pandas as pd
>>> import scanpy as sc
>>> import anndata as ad
>>> 
>>> import muon as mu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/naseersangwan/Desktop/Conda/envs/R_2024/lib/python3.9/site-packages/muon/__init__.py", line 6, in <module>
    from ._core import preproc as pp
  File "/Users/naseersangwan/Desktop/Conda/envs/R_2024/lib/python3.9/site-packages/muon/_core/preproc.py", line 15, in <module>
    from scanpy.neighbors import _compute_connectivities_umap
ImportError: cannot import name '_compute_connectivities_umap' from 'scanpy.neighbors' (

**Comment by bio-la** [comment]
hi, got the same error since updating scanpy in the last 12 hours
`scanpy 1.10.0,  muon 0.1.5,  anndata 0.8.0`

**Comment by dorzhey** [comment]
hello, yes same dependencies, same problem

**Comment by WLYYYYY** [comment]
Same here, it seems like the last version of Scanpy compatible with muon is v1.9.8.

**Comment by seyoon-lee** [comment]
seems like I'm two weeks late, but still with the same issue.

**Comment by zijunmeng** [comment]
same errors with scanpy  1.10.1, muon  0.1.5, anndata 0.10.6 ,

**Comment by grst** [comment]
Oh, I think we still need a patch release @gtca?

**Comment by gtca** [comment]
@grst, the `0.1.5` is the version for which this issue has been open for, the `0.1.6` [has already been released](https://pypi.org/project/muon/0.1.6/) to fix that for the new version of scanpy.

@zijunmeng, can you check that it fixed the issue for you?

**Comment by grst** [comment]
Sorry, got confused by that release missing on github. But I've seen it's there now :)

**Comment by zijunmeng** [comment]
> @grst, the `0.1.5` is the version for which this issue has been open for, the `0.1.6` [has already been released](https://pypi.org/project/muon/0.1.6/) to fix that for the new version of scanpy.
> 
> @zijunmeng, can you check that it fixed the issue for you?

yes, thank you, i have solved this problem. In my env, I have installed scvi, scglue, and muon. Two days ago, I encountered conflicts between muon's functions and scvi. I have now uninstalled the original 0.1.5 version and reinstalled the 0.1.6 version using pip. The conflicts have indeed disappeared. Thank you again for your help.
