### ISSUE TITLE
CITE-seq scatter plot of pairwise RNA-prot correlations

### ISSUE THREAD

**Issue by chris-rands** [scverse/muon#48]
Thanks for muon. Following the CITE-seq tutorial, I'd like to do simple scatter plots and regression to show the RNA-prot correlation for particular markers, something like in the Seurat [muli-modal tutorial.](https://satijalab.org/seurat/articles/multimodal_vignette.html):
![image](https://user-images.githubusercontent.com/20436557/150566409-bfaecc51-c7e3-4cf1-943b-7434157b767e.png)

I tried `sc.pl.scatter(mdata, x="prot:CD3D", y="rna:CD3D")` This raises: `KeyError: 'There is no key prot:CD3D in MuData .obs or in .obs of any modalities.'` Of course the gene/protein names are stored in `.var` not `.obs`. 

Suggestions appreciated, thank you

**Comment by gtca** [comment]
Hey @chris-rands, thanks a lot for your feedback! The reason was the lack of `.pl.scatter` in `muon`.
Now `mu.pl.scatter(mdata, ...)` should work.

Moreover, for this there's now a more sophisticated function under the hood to parse variables so even the following things should work:

```python
mu.pl.scatter(mdata, x="X_umap:1", y="X_umap:2", color="CD8A")
# will produce a plot similar to mu.pl.umap(mdata, color="CD8A")

mu.pl.scatter(mdata, x="CD8A", y="CD8a_TotalSeqB", color="rna:X_umap:1")
# will set the colour to the first UMAP component in the RNA modality
```

It also seems to me that https://github.com/theislab/scanpy/issues/311 hasn't been actually fixed — is that your experience as well?

Please let me know what you think!

**Comment by gtca** [comment]
Hey @chris-rands, glad that it works! And thanks for your feedback.
Now it should handle the case when `var_names` have a modality prefix correctly.
Moreover, now the same functionality should work even when some modalities have cells that are not present in others (e.g. the `'rna'` modality has more cells than `'prot'` modality does).

With regression, if this was implemented e.g. in `sc.pl.scatter`, `mu.pl.scatter` would just work (or we could at least build on top of that). I am not sure this is something coming in `sc.pl.scatter` though. One might want to overlay other interpolations, or exclude cells with missing values (e.g. with zero CD3E expression in the plot above) from the fit, and all this can be achieved e.g. with `matplotlib` although would require a few more lines of code:

```py
# Calculate coefficients for the regression line
from numpy.polynomial.polynomial import polyfit
x = mdata["rna"][:,"CD3E"].X.squeeze()
y = mdata["prot"][:,"CD3_TotalSeqB"].X.squeeze()
a, b = polyfit(x, y, deg=1)

# Plot data
mu.pl.scatter(mdata, x="CD3E", y="CD3_TotalSeqB", show=False)
# Plot regression line and display the figure
plt.plot(x, a + b * x, "-")
plt.show()
```
