### ISSUE TITLE
Error in mu.tl.mofa

### ISSUE THREAD

**Issue by Chengwei94** [scverse/muon#52]
**Describe the bug**
 Value passed for key 'LFs' is of incorrect shape. Values of varm must match dimensions (1,) of parent. Value had shape (61452, 10) while it should have had (150850,)

**To Reproduce**
mu.tl.mofa(mudata)

**Additional context**
The mudata object is not updated if I subset either the rna or atac slot. As you can see here, the MuData is still 150k features but atac + rna is only 60k features.  The object is only updated when its written and read again 

MuData object with n_obs × n_vars = 7098 × 150850 
    rna:	7098 x 21894
      obs:	'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'celltype'
      var:	'gene_ids', 'feature_types', 'genome', 'interval', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm', 'mean', 'std'
      uns:	'hvg', 'log1p', 'pca', 'neighbors', 'umap'
      obsm:	'X_pca', 'X_umap'
      varm:	'PCs'
      layers:	'counts'
      obsp:	'distances', 'connectivities'
    atac:	7098 x 39558
      obs:	'n_genes_by_counts', 'total_counts', 'nucleosome_signal', 'tss_score'
      var:	'gene_ids', 'feature_types', 'genome', 'interval', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
      uns:	'atac', 'files', 'hvg', 'lsi', 'neighbors', 'umap'
      obsm:	'X_lsi', 'X_umap'
      varm:	'LSI'
      layers:	'counts'
      obsp:	'distances', 'connectivities'

**Comment by Chengwei94** [comment]
Turns out I can use mudata.update() to update the file

**Comment by gtca** [comment]
Just to add a comment here, we've already started documenting such _gotchas_ in the documentation:
https://mudata.readthedocs.io/en/latest/notebooks/nuances.html#Update. 🙂
