### ISSUE TITLE
Shape Issue with mu.tl.mofa

### ISSUE THREAD

**Issue by Chadmiumoxid** [scverse/muon#61]
Dear Muon Team,

I used your program with great success (really great usability!), up until I wanted to integrate the RNA and ATAC data into a joint latent space.
My object looks as following:

muData object with n_obs × n_vars = 9817 × 304944
  obs:	'sample'
  var:	'feature_types', 'genome'
  2 modalities
    rna:	9817 x 16660
      obs:	'sample', 'int_id', 'seq_id_gex_id', 'seq_id_atac', 'reporter', 'n_counts', 'log_cell_probs', 'cell_confirmed', 'log_counts', 'n_genes', [...]
      var:	'gene_ids', 'feature_types', 'genome', 'interval', 'n_cells-0', 'ambient_genes_values-0', 'is_ambient-0', 'is_ambi_key-0', 
[...]
      uns:	'final_doublets_cat_colors', 'louvain', 'louvain_3_colors', 'louvain_colors', 'neighbors', 'reporter_colors', 'sample_colors', 'batch_colors', 'log1p', 'umap'
      obsm:	'X_pca', 'X_umap'
      layers:	'counts'
      obsp:	'connectivities', 'distances'
    atac:	9817 x 288284
      obs:	'seurat_id', 'aggr_barcodes', 'sample', 'int_id', 'seq_id_gex_id', 'seq_id_atac', 'reporter', 'size_factors', 'louvain'
      var:	'feature_types', 'modality', 'genome'
      uns:	'files', 'log1p', 'neighbors', 'louvain', 'umap', 'sample_colors'
      obsm:	'X_pca', 'X_umap'
      layers:	'counts'
      obsp:	'distances', 'connectivities' 

When I then try to run 
`mu.tl.mofa(mdata2, groups_label = 'sample')`
the result is always the same with:

> ValueError:` shapes (9817,16660) and (9817,16660) not aligned: 16660 (dim 1) != 9817 (dim 0) 

And I just cant make sense of it. Thank you very much for your help!

**Comment by gtca** [comment]
Hey @Chadmiumoxid, great to hear you find it useful!

Is there any code to reproduce this issue?

Here is some code to run MOFA on two groups of data with 2 views, and it seems to work:

```python
import jax
import numpy as np

z = jax.random.normal(key=jax.random.PRNGKey(1), shape=(100,3)) * jax.numpy.array([2, 3, 4])
w = jax.random.normal(key=jax.random.PRNGKey(1), shape=(3,200))
y = z @ w

a1 = AnnData(np.array(y[:,:150]))
a2 = AnnData(np.array(y[:,150:]))
mdata = MuData({"a1": a1, "a2": a2})
mdata.var_names_make_unique()

mdata.obs["group"] = jax.random.choice(key=jax.random.PRNGKey(1), a=jax.numpy.array([0, 1]), shape=(100,))
mdata.obs.group = mdata.obs.group.astype(str)
mu.tl.mofa(mdata, groups_label="group")

mdata.obsm["X_mofa"].shape
# => (100, 10)
```

**Comment by Chadmiumoxid** [comment]
Well, my code is as following: I have the feeling its a problem with the architecture of my file (making it hard to reproduce remotely) yet I dont really understand the nature of the problem

```
mdata = mu.MuData({'rna': mdata.mod['rna'], 'atac': mdata.mod['cr_aggr']})

mu.pp.intersect_obs(mdata)

mu.tl.mofa(mdata, groups_label = 'sample', n_factors=50, use_float32 = True, seed=2022, verbose=True,

           quiet=False, gpu_mode = False)


        #########################################################
        ###           __  __  ____  ______                    ### 
        ###          |  \/  |/ __ \|  ____/\    _             ### 
        ###          | \  / | |  | | |__ /  \ _| |_           ### 
        ###          | |\/| | |  | |  __/ /\ \_   _|          ###
        ###          | |  | | |__| | | / ____ \|_|            ###
        ###          |_|  |_|\____/|_|/_/    \_\              ###
        ###                                                   ### 
        ######################################################### 
       
 
        
use_float32 set to True: replacing float64 arrays by float32 arrays to speed up computations...

Loaded view='rna' group='FVRminus' with N=5211 samples and D=16660 features...
Loaded view='rna' group='FVRplus' with N=4606 samples and D=16660 features...
Loaded view='atac' group='FVRminus' with N=5211 samples and D=288284 features...
Loaded view='atac' group='FVRplus' with N=4606 samples and D=288284 features...


Model options:
- Automatic Relevance Determination prior on the factors: True
- Automatic Relevance Determination prior on the weights: True
- Spike-and-slab prior on the factors: False
- Spike-and-slab prior on the weights: True
Likelihoods:
- View 0 (rna): gaussian
- View 1 (atac): poisson


Convergence mode: fast



######################################
## Training the model with seed 2022 ##
######################################


 ValueError: shapes (9817,16660) and (9817,16660) not aligned: 16660 (dim 1) != 9817 (dim 0) 

```

**Comment by Chadmiumoxid** [comment]
Thank you for your help.
The version is 0.1.2 for muon and 0.6.4 for mofapy2.

The more detailed ValueError is as following:

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [53], in <cell line: 1>()
----> 1 mu.tl.mofa(mdata, n_factors=4,
      2            outfile="models/mefisto_ST.hdf5",
      3            use_float32=True, seed=2021,
      4            quiet=False)

File ~/miniconda3/envs/sc1.9ATAC/lib/python3.8/site-packages/muon/_core/tools.py:540, in mofa(data, groups_label, use_raw, use_layer, use_var, use_obs, likelihoods, n_factors, scale_views, scale_groups, center_groups, ard_weights, ard_factors, spikeslab_weights, spikeslab_factors, n_iterations, convergence_mode, gpu_mode, use_float32, smooth_covariate, smooth_warping, smooth_kwargs, save_parameters, save_data, save_metadata, seed, outfile, expectations, save_interrupted, verbose, quiet, copy)
    538 ent.build()
    539 logging.info(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Running the model...")
--> 540 ent.run()
    542 if (
    543     smooth_kwargs is not None
    544     and "new_values" in smooth_kwargs
    545     and smooth_kwargs["new_values"]
    546     and smooth_covariate
    547 ):
    548     logging.info(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Interpolating factors...")

File ~/miniconda3/envs/sc1.9ATAC/lib/python3.8/site-packages/mofapy2/run/entry_point.py:49, in keyboardinterrupt_saver.<locals>.saver(self, *args, **kwargs)
     46 @wraps(func)
     47 def saver(self, *args, **kwargs):
     48     try:
---> 49         func(self, *args, **kwargs)
     50     # Internal methods will raise TypeError when interrupted
     51     except (KeyboardInterrupt, TypeError):

File ~/miniconda3/envs/sc1.9ATAC/lib/python3.8/site-packages/mofapy2/run/entry_point.py:1020, in entry_point.run(self)
   1017 self.model.setTrainOptions(self.train_opts)
   1019 # Train the model
-> 1020 train_model(self.model)

File ~/miniconda3/envs/sc1.9ATAC/lib/python3.8/site-packages/mofapy2/build_model/train_model.py:28, in train_model(model)
     25 print ("#"*38)
     26 print ("\n")
---> 28 model.iterate()
     30 print("\n")
     31 print("#"*23)

File ~/miniconda3/envs/sc1.9ATAC/lib/python3.8/site-packages/mofapy2/core/BayesNet.py:224, in BayesNet.iterate(self)
    217 # keep track of factor-wise training statistics (attribute as needs to be accounted for in factor dropping)
    218 # if 'Sigma' in self.nodes.keys():
    219 #     self.lscales = pd.DataFrame(data = nans((self.options['maxiter'], self.dim['K'])), columns = range(self.dim['K']))
    220 #     self.scales = pd.DataFrame(data = nans((self.options['maxiter'], self.dim['K'])), columns = range(self.dim['K']))
    221 
    222 # Precompute
    223 converged = False; convergence_token = 1
--> 224 elbo.iloc[0] = self.precompute()
    225 number_factors[0] = self.dim['K']
    226 iter_time[0] = 0.

File ~/miniconda3/envs/sc1.9ATAC/lib/python3.8/site-packages/mofapy2/core/BayesNet.py:197, in BayesNet.precompute(self)
    195 # Precompute ELBO
    196 for node in self.nodes["Y"].getNodes(): node.TauTrick = False # important to do this for ELBO computation
--> 197 elbo = self.calculateELBO()
    198 for node in self.nodes["Y"].getNodes(): node.TauTrick = True
    200 if self.options['verbose']:

File ~/miniconda3/envs/sc1.9ATAC/lib/python3.8/site-packages/mofapy2/core/BayesNet.py:412, in BayesNet.calculateELBO(self, *nodes)
    410 for node in nodes:
    411     if isinstance(self.nodes[node], Multiview_Variational_Node):
--> 412         elbo[node] = float(self.nodes[node].calculateELBO(weights = weights))
    413     else:
    414         elbo[node] = float(self.nodes[node].calculateELBO())

File ~/miniconda3/envs/sc1.9ATAC/lib/python3.8/site-packages/mofapy2/core/nodes/multiview_nodes.py:164, in Multiview_Mixed_Node.calculateELBO(self, weights)
    162 for m in self.activeM:
    163     if isinstance(self.nodes[m],Variational_Node):
--> 164         lb += self.nodes[m].calculateELBO() * weights[m]
    165 return lb

File ~/miniconda3/envs/sc1.9ATAC/lib/python3.8/site-packages/mofapy2/core/nodes/Y_nodes.py:98, in Y_Node.calculateELBO(self)
     92 W, WW = Wtmp["E"].T, Wtmp["E2"].T
     93 Z, ZZ = Ztmp["E"], Ztmp["E2"]
     95 tmp = s.square(Y) \
     96     + ZZ.dot(WW) \
     97     - s.dot(s.square(Z),s.square(W)) + s.square(Z.dot(W)) \
---> 98     - 2*Z.dot(W)*Y 
     99 tmp *= 0.5
    100 tmp[mask] = 0.

File ~/miniconda3/envs/sc1.9ATAC/lib/python3.8/site-packages/numpy/matrixlib/defmatrix.py:224, in matrix.__rmul__(self, other)
    223 def __rmul__(self, other):
--> 224     return N.dot(other, self)

File <__array_function__ internals>:5, in dot(*args, **kwargs)

ValueError: shapes (9817,288284) and (9817,288284) not aligned: 288284 (dim 1) != 9817 (dim 0)

`

**Comment by gtca** [comment]
I didn't manage to reproduce it so far. Maybe there's a clean conda environment you can try it in, or there's a way to share some minimal data that goes into training. (I assume the same happens for a MuData object with just a few cells and genes / peaks.)

Are there sparse matrices involved by any chance?..

P.S. BTW, you might want to perform feature selection as factorising matrices with >200k features might take quite some time.
