### ISSUE TITLE
High Cpu Usage

### ISSUE THREAD

**Issue by liujilei156231** [scverse/muon#62]
Hello,
when I ran `mu.pp.neighbors(mdata)`,cpu was used 100%.
So how to set up same parameters to prevent HIGH CPU USAGE?

`python 3.7 with latest muon`

Thanks!

![image](https://user-images.githubusercontent.com/62644866/175847263-3f364678-8f82-49dd-b0ab-fb2cd3f8e606.png)

**Comment by gtca** [comment]
Hey @liujilei156231, this is probably something not specific to `mu.pp.neighbors`.
Seems like you can [impose resource usage limits](https://docs.python.org/3/library/resource.html) in Python with `setrlimit`. I guess this might be relevant for local development and less so for HPC systems.

**Comment by 111kakaluote** [comment]
mu.pp.neighbors always use more computing resoure than sc.pp.neighbors, and core dumped, and how to solve it;

**Comment by gtca** [comment]
Hey @111kakaluote, `mu.pp.neighbors` has a different use case and implements a different algorithm than `sc.pp.neighbors`, [namely WNN](https://doi.org/10.1016/j.cell.2021.04.048). So different resource usage is expected.

What are the rough dimensions of the dataset that multimodal neighbours are computed on?
