### ISSUE TITLE
ATACseq+RNAseq Integration Tutorial Error Loading Data

### ISSUE THREAD

**Issue by the-rich-piana** [scverse/muon#63]
**Describe the bug**
Hi there, I am not sure if this is a bug, but I cannot seem to run [this tutorial](https://muon-tutorials.readthedocs.io/en/latest/single-cell-rna-atac/pbmc10k/1-Gene-Expression-Processing.html) locally. 

See screenshots below:
[Not loading the 'files' ATAC unstructured annotation ](https://gyazo.com/9a8bacbf77a0d909bb339271c763dd7b)
[Correct importing of data, according to tutorial ](https://gyazo.com/c4b1cb100835c8dba7ccb208cd396c61)
Everything works fine up until the ATACseq analysis part. 

I get a key error related to 'files'. Which is supposed to be an unstructured annotation in Anndata. 

```
atac.obs['NS'] = 1 
ac.pl.fragment_histogram(atac, region='chr1:1-2000000')
```
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [37], in <cell line: 2>()
      1 atac.obs['NS'] = 1 
----> 2 ac.pl.fragment_histogram(atac, region='chr1:1-2000000')

File ~/mambaforge/envs/bioinfo/lib/python3.10/site-packages/muon/_atac/plot.py:341, in fragment_histogram(data, region, groupby, barcodes)
    338 else:
    339     raise TypeError("Expected AnnData or MuData object with 'atac' modality")
--> 341 fragment_path = adata.uns["files"]["fragments"]
    342 fragments = tools.fetch_regions_to_df(fragment_path=fragment_path, features=region)
    344 fragments["length"] = fragments.End - fragments.Start

File ~/mambaforge/envs/bioinfo/lib/python3.10/site-packages/anndata/compat/_overloaded_dict.py:100, in OverloadedDict.__getitem__(self, key)
     98     return self.overloaded[key].get()
     99 else:
--> 100     return self.data[key]

KeyError: 'files'
```

I assume this is related to the fact that I have a different directory structure, or that somehow I have downloaded the wrong files from 10X Genomics.

**System**
 - OS: Ubuntu 20.04
 - Python version: 3.8
 - Versions of libraries involved: Mamba environment with latest Muon version.

Any help is appreciated.
Thanks,
Giuliano.

**Comment by gtca** [comment]
Hey @the-rich-piana,

Not sure yet what's happening there. Can you check what `atac.uns` shows calling it before the `ac.pl.fragment_histogram` line? It looks like `mdata["atac"]` has `.uns["files"]` but the object `atac` doesn't?..

**Comment by the-rich-piana** [comment]
Thanks for answering. 

It looks like `atac.uns` and `mdata['atac'].uns` have the peak annotations. But again no mention of "files".
![image](https://user-images.githubusercontent.com/15808990/176943244-35e0753c-ec6f-41f9-a850-1d627405e5b8.png)
Running `mdata["atac"].uns["files"]` throws the same keyerror.
![image](https://user-images.githubusercontent.com/15808990/176944102-41777067-fdd9-4b12-b880-be3a95c8fca3.png)

Any idea what the "files" data is supposed to be?

**Comment by gtca** [comment]
Thanks, @the-rich-piana!
It might be that in earlier versions fragments file location wasn't saved to `.uns["files"]` if `pysam` wasn't installed, which was indicated in the first screenshot in the original message, but that's just a guess.

Currently, you can try running `ac.tl.locate_fragments(atac, "data/pbmc10k/atac_fragments.tsv.gz")`. It basically just puts the location of the fragments file into `.uns["files"]` as `muon.atac` works with fragments directly from disk rather than loading them into memory.
To work with that file, `pysam` will be needed.

**Comment by the-rich-piana** [comment]
Awesome Pysam worked. Thanks so much, I appreciate your help.

**Comment by jondeans** [comment]
I would suggest adding `pysam` to a requirement of muon or at least noting at the beginning of this tutorial that it should be installed in the environment to run the tutorial completely. 

I am running the tutorial in Colab with a custom directory structure (via google drive) and the locate fragments step is useless with out pysam in the environment 

After installing `pysam` with pip, everything is okay, but this could be easily avoided in the future, IMO.
