### ISSUE TITLE
Use a representation from mudata.obsm to calculate neighbors

### ISSUE THREAD

**Issue by alitinet** [scverse/muon#67]
Hi,

is there an easy way to use e.g. `mdata.obsm['X_mofa']` representation to calculate neighbors? Now I create a new AnnData object from the representation, calculate neighbors with `sc.pp.neighbors()`, and then store the connectivities and distances in the `mdata.obsp`, but it would be nice to have a wrapper around this in muon. Thanks!

**Comment by gtca** [comment]
Hey @alitinet,

I believe it should already be possible to do that, e.g.

```python
import scanpy as sc
import muon as mu

mdata = mu.read("pbcm5k_citeseq.h5mu")
sc.pp.neighbors(mdata, use_rep="X_mofa", key_added="mofa")
mdata.obsp
# => PairwiseArrays with keys: mofa_distances, mofa_connectivities
```

As `sc.pp.neighbors` takes a representation from `.obsm[use_rep]`, calculates cell neighbours and writes the graphs to `.obsp[...]`, it should just work on a MuData object. [In the tutorials](https://muon-tutorials.readthedocs.io/en/latest/cite-seq/1-CITE-seq-PBMC-5k.html#Multi-omics-factor-analysis) it is also something that is computed prior to running `sc.tl.umap`.

Is that what you had in mind?..

**Comment by alitinet** [comment]
Hi, ah I see, sorry I didn't realize that you can just run `sc.pp.neighbors` on mdata objects and not only on the modality anndatas! thanks!
