### ISSUE TITLE
missing index file atac fragments 

### ISSUE THREAD

**Issue by bio-la** [scverse/muon#71]
Hi, probably a long shot but I need to re-analyse the Teaseq dataset that you use in your [multimodal vignette](https://muon-tutorials.readthedocs.io/en/latest/trimodal/tea-seq/1-TEA-seq-PBMC.html) but I can't find the .tbi index (data/teaseq/GSM5123951_X066-MP0C1W3_leukopak_perm-cells_tea_200M_atac_filtered_fragments.tsv.gz.tbi)  for the atac fragment files on geo. https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE158013

do you happen to have these files and could share them?
thank you!

**Comment by ivirshup** [comment]
Would you be able to recreate this with `tabix`?

**Comment by bio-la** [comment]
yes thank you! this was very silly -.-'
