### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by msenosain** [scverse/muon#73]
When I try to import muon I get this error
"Illegal instruction: 4"

I've read this happened in other packages like tensor flow in users with M1 and M1 Pro chips, although there is no clear solution. I've updated my OS to the latest (macOS Monterey 12.6) but the bug persists. My laptop has an M1 Pro chip. Not sure if this is something that the developers can fix but just wanted to put it out there in case someone else encounters the same issue.

**Comment by msenosain** [comment]
This fix is suggested for TF but worked for muon in my case [https://developer.apple.com/metal/tensorflow-plugin/](https://developer.apple.com/metal/tensorflow-plugin/)

**Comment by gtca** [comment]
Thanks a lot, I added this [to the documentation](https://muon.readthedocs.io/en/latest/install.html#id3).
