### ISSUE TITLE
GPU not found

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/muon#75]
Hi,
I tried to run mofa mu.tl.mofa(mdata,n_factors=20,outfile="brain3k_mofa_model.hdf5",gpu_mode=True)
but an error occurred:
GPU mode is activated, but GPU not found... switching to CPU mode
For GPU mode, you need:
1 - Make sure that you are running MOFA+ on a machine with an NVIDIA GPU
2 - Install CUPY following instructions on https://docs-cupy.chainer.org/en/stable/install.html
I have already installed CUPY following the instructions and I am sure GPU is available when using pytorch. what's the reason ?

**Comment by gtca** [comment]
Hey @wangjiawen2013,

Not sure this is enough information to diagnose the issue.

MOFA relies on CUPY for GPU-related training. Does the following also work as you'd expect in the same environment and on the same machine?

```py
import cupy as cp
print(cp.cuda.runtime.getDeviceCount())
```
