### ISSUE TITLE
Batch correction with MOFA

### ISSUE THREAD

**Issue by alitinet** [scverse/muon#77]
Hi,

I wanted to double check that I'm running MOFA correctly. I have two batches in my data and the function I'm using is
```
mu.tl.mofa(mdata, groups_label='batch', gpu_mode=True)
```

The resulting UMAP looks like this. Is this the correct way to run MOFA on batches? Thanks!
![umap_mofa](https://user-images.githubusercontent.com/20745228/195378817-b7f1eeab-caac-4b9c-9e29-94381af053fe.jpg)

**Comment by gtca** [comment]
Hey @alitinet,

Yes, that looks like the way to use grouping by `"batch"`.
There still might be factors that are correlated with the batch. Would identifying such factors based on a correlation matrix and then not using them when computing the UMAP embedding help?

**Comment by alitinet** [comment]
Hi @gtca, this is exactly what I wanted to double check, thanks!
