### ISSUE TITLE
Add link to GitHub page on Muon docs

### ISSUE THREAD

**Issue by gregjohnso** [scverse/muon#78]
**Is your feature request related to a problem? Please describe.**
It is not easy to find the `muon` GitHub page from the [`muon` docs](https://muon.readthedocs.io/en/latest/)

**Describe the solution you'd like**
Add a link to the `muon` GitHub page on https://muon.readthedocs.io/en/latest/

**Comment by gtca** [comment]
Thanks for noticing! I added a link to the repository to the front page of the documentation, which could probably benefit from some more attention beyond that...
