### ISSUE TITLE
raise error when mu.pp.neighbors

### ISSUE THREAD

**Issue by 111kakaluote** [scverse/muon#82]
**Describe the bug**
<img width="729" alt="1671760010428" src="https://user-images.githubusercontent.com/22848256/209254569-f159abb1-cbf1-4d82-a187-658d0c1e0721.png">

**System**
 - OS: [e.g. macOS Big Sur]
 - Python 3.8
 - Anndata 0.7.8
 - muon 0.1.2
 - scanpy 1.8.2
 - mudata 0.1.2
 - scipy 1.9.3

**Comment by Zethson** [comment]
Please provide more details to allow us to understand and reproduce the error.

**Comment by 111kakaluote** [comment]
> Please provide more details to allow us to understand and reproduce the error.

Sorry, this error produced because of the misoperation when merged the two cite-seq datasets, and now I soved it.
