### ISSUE TITLE
`sklearn` vs `scikit-learn`

### ISSUE THREAD

**Issue by gjhuizing** [scverse/muon#91]
Hi, my CI deployments fail because Muon's latest release depends on `sklearn` instead of `scikit-learn`. I see this has been changed 5 months ago but not yet integrated in a new release. Please consider updating the version available via PyPI :)

**To Reproduce**
Install Muon on a clean VM.

**Comment by gtca** [comment]
Thanks, @gjhuizing! v0.1.3 should be there soon to fix it.

**Comment by gjhuizing** [comment]
Thanks @gtca!

**Comment by Zethson** [comment]
@gtca just want to add a bit more respectful pressure here since this is actually killing the installation of pertpy atm and surely other packages.

Could we get this out ASAP?

Thank you!

**Comment by gtca** [comment]
This should fix it: https://pypi.org/project/muon/0.1.3/.
