### ISSUE TITLE
Tutorial Problem: MOFA_loadings does not work as it is not included in source code ? Also, Kernel Crashing when mu.pp.neighbors(mdata, key_added='wnn')

### ISSUE THREAD

**Issue by maxwellkonnaris** [scverse/muon#94]
**Describe the bug**
I am fully able to run the tutorial as provided by the authors on the PBMC Tea-Seq multi-modal analysis. However, when I run mofa_loadings, this does not compute as it states the error: method unavailable. I checked the source code and it is not included in mu.pl.

Also, and more importantly, when I run the WNN algorithm using mu.pp.neighbors(mdata, key_added='WNN') the kernal crashes. I thought maybe this was a memory problem so I ran this with 160GB of RAM. Same issue. Why is this kernal crashing? 

I have ran all code exactly the same way as in the tutorial.

Thank you! let me know if you need any additional information.

**To Reproduce**
Run the tutorial as provided here: 

https://muon-tutorials.readthedocs.io/en/latest/trimodal/tea-seq/1-TEA-seq-PBMC.html#Weighted-nearest-neighbours

**Expected behaviour**
WNN runs as expected.

**System**
 - OS: [e.g. macOS Big Sur] ----- I've ran on macOS, but also on Linux
 - Python version [e.g. 3.8] --- Python 3.9.16
 - Versions of libraries involved [e.g. AnnData 0.7.4] ------ Just installed latest version of each.

**Comment by gtca** [comment]
Hey @maxwellkonnaris,

- `mu.pl.mofa_loadings()` is there — probably a earlier version (<0.1.3) was installed. 
- I haven't been able to reproduce the crashed kernel when running `mu.pp.neighbors()`. Does it also crash for you when running it on a small data subset? Are there any logs that you can share, whether here or in private messages?

**Comment by gtca** [comment]
Closing as stale, please feel free to reopen or open a new one.
